### ISSUE TITLE
Saves Deleted?

### ISSUE THREAD

**Issue by LordDarcade** [AlderArts/foe#364]
For some reason when I came back to FoE to load my save, the "Load Game" button was greyed out, help please?

**Comment by LordDarcade** [comment]
I am using Safari btw

**Comment by CalmKhaos** [comment]
http://fenoxo.com/forum/index.php?/topic/143-restoring-saves-in-chrome/

**Comment by aldergames** [comment]
I can understand you frustration, but this isn't something in my control. Most likely, it was caused by the server move, but saves are stored locally in your browser. If they aren't gone due to clearing cache, try following the linked instructions (not sure what the exact details would be in Safari, I don't use the browser).

Try to keep a local copy (save to file/text) in the future.
